services:
  twingate:
    image: docker.io/twingate/connector:latest
    
    
    restart: unless-stopped
    container_name: twingate_connector
    
    
    hostname: twingate_connector
    
    environment:
      - TZ=
      - TWINGATE_NETWORK=
      
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN:?error}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN:?error}
      
      - TWINGATE_LOG_LEVEL=1
      
    
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    
    



