services:
  gitea:
    image: docker.io/gitea/gitea:latest
    restart: unless-stopped
    environment:
      - USER_UID=
      - USER_GID=
      
      - GITEA__database__DB_TYPE=
      
      - GITEA__database__HOST=gitea_db
      
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${DATABASE_PASSWORD}
      
      - GITEA__server__SSH_PORT=2221
      
      - GITEA__server__ROOT_URL=https://git.example.com
      
    
    ports:  
      
      - "3000:3000"
      
      - "2221:22"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    
    
    depends_on:
      - gitea_db
    

  

volumes:
  gitea_data:
    driver: local
  
  
  


