---
services:
  pihole:
    image: docker.io/pihole/pihole:latest
    
    
    restart: unless-stopped
    
    container_name: pihole
    
    
    
    
    
    environment:
      - TZ=
      - PIHOLE_UID=
      - PIHOLE_GID=
      
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
      
      
    
    
    
    
    ports:
      
      
      - "80:80/tcp"
      - "443:443/tcp"
      
      
      
      - ":53/tcp"
      - ":53/udp"
      - "123:123/udp"
      
    
    
    volumes:
      
      - pihole-dnsmasq:/etc/dnsmasq.d
      - pihole-pihole:/etc/pihole
      
    
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    
    
    
    
    
    









