---
services:
  :
    image: docker.io/library/influxdb:latest
    restart: unless-stopped
    environment:
      - TZ=
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
    
    
    ports:
      - "8086:8086"
    
    volumes:
      - _data:/var/lib/influxdb2
    
    
volumes:
  _data:
    driver: local


