services:
  postgres:
    image: docker.io/library/postgres:latest
    
    
    restart: unless-stopped
    container_name: postgres
    
    
    hostname: 
    
    environment:
      - POSTGRES_INITDB_ARGS=
      
      - POSTGRES_USER=
      
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
      - POSTGRES_DB=
      - TZ=
    
    
    networks:
      postgres_network:
    
    
    
    ports:
      
      - ":5432"
      
    
    
    volumes:
      
      - postgres-data:/var/lib/postgresql/data
      
    
    
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U "]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    
    






volumes:
  postgres-data:
    driver: local




networks:
  postgres_network:
    
    
    driver: bridge
    
    

