---
services:
  whoami:
    image: traefik/whoami:latest
    
    restart: unless-stopped
    
    
    labels:
      - traefik.enable=true
      - traefik.docker.network=
      - traefik.http.services.whoami-web.loadbalancer.server.port=80
      - traefik.http.routers.whoami-http.service=whoami-web
      - traefik.http.routers.whoami-http.rule=Host(`whoami.`)
      - traefik.http.routers.whoami-http.entrypoints=web
      
    
    networks:
      - 

networks:
  :
    external: true
