services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    
    restart: unless-stopped
    
    environment:
      - TZ=
    
    ports:
    
      - "9000:9000"
      - "9443:9443"
    
      - "8000:8000"
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      
      - portainer_data:/data
      
    
    




