---
services:
  passbolt:
    image: docker.io/passbolt/passbolt:latest
    restart: unless-stopped
    environment:
      
      - APP_FULL_BASE_URL=https://passbolt.domain.tld
      - DATASOURCES_DEFAULT_HOST=passbolt-db
      - DATASOURCES_DEFAULT_USERNAME=$PASSBOLT_DB_USER
      - DATASOURCES_DEFAULT_PASSWORD=$PASSBOLT_DB_PASS
      - DATASOURCES_DEFAULT_DATABASE=$PASSBOLT_DB_NAME
      - EMAIL_TRANSPORT_DEFAULT_HOST=your-mail-server
      - EMAIL_TRANSPORT_DEFAULT_PORT=587
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=$EMAIL_TRANSPORT_DEFAULT_USERNAME
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=$EMAIL_TRANSPORT_DEFAULT_PASSWORD
      - EMAIL_TRANSPORT_DEFAULT_TLS=true
      - EMAIL_DEFAULT_FROM=no-reply@domain.tld
    volumes:
      - passbolt-gpg:/etc/passbolt/gpg
      - passbolt-jwt:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "passbolt-db:3306", "--", "/docker-entrypoint.sh"]
    depends_on:
      - passbolt-db

  passbolt-db:
    image: docker.io/library/mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=$PASSBOLT_DB_NAME
      - MYSQL_USER=$PASSBOLT_DB_USER
      - MYSQL_PASSWORD=$PASSBOLT_DB_PASS
    volumes:
      - passbolt-db:/var/lib/mysql


volumes:
  passbolt-db:
  passbolt-gpg:
  passbolt-jwt:
