services:
  alloy:
    image: docker.io/grafana/alloy:latest
    restart: unless-stopped
    
    
    
    ports:
      - "12345:12345"
    
    volumes:
      - alloy_data:/alloy/data
      - ./config.alloy:/etc/alloy/config.alloy:ro
      
      
      
      
    



volumes:
  alloy_data:
    driver: local
