services:
  nginx:
    image: docker.io/library/nginx:latest
    
    
    restart: unless-stopped
    container_name: nginx
    
    
    
    
    
    ports:
      
      - "8080:80"
      - "8443:443"
      
    
    
    # volumes:
    #   - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    #   - ./data:/usr/share/nginx/html:ro
    
    
    
    



