services:
  -app:
    image: docker.io/library/nextcloud:latest
    
    restart: unless-stopped
    container_name: -app
    
    environment:
      - TZ=
      
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_HOST=-db
      

    
    ports:
      
      - "80:80"
      
    
    volumes:
      - nextcloud-data:/var/www/html
    
    depends_on:
      - -db
    

  -db:
    
    image: docker.io/library/postgres:latest
    
    restart: unless-stopped
    container_name: -db
    
    environment:
      - TZ=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=
    
    volumes:
      - nextcloud-db:/var/lib/postgresql/data

    

volumes:
  nextcloud-data:
    driver: local
  nextcloud-db:
    driver: local

networks:
  

